spring.application.name=Net_Banking_Chandu
server.port=200



spring.datasource.url=jdbc:mysql://localhost:3306/net_banking
spring.datasource.username=root
spring.datasource.password=Chandu@7893

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false